---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://releases.rancher.com/server-charts/latest
      chart: rancher
      version: 2.6.3
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
      interval: 3m
  values:
    hostname: "rancher.${SECRET_DOMAIN}"
    ingress:
      enabled: true
      hostname: "rancher.${SECRET_DOMAIN}"
      extraAnnotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/appName: "rancher"
        hajimari.io/enable: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      tls:
        secretName: "rancher-tls"
        source: letsEncrypt
    letsEncrypt:
      ingress:
        class: "traefik"
