kind: Secret
ansible_user: ENC[AES256_GCM,data:EB8=,iv:ZlMUZmd+RDehFiOmxtalGHmRKQAPFAP4MN3F2/eioWc=,tag:cqiPRr5aBfDVGlMRQWDAnw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:4Gk7M9XWew==,iv:W5hg4PPD60IVrLop26h5hwX2mrLHqMR9VoVM5cz8gu8=,tag:PHtnent8FVUkeEHbh/SvWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lhe4v2xrzmjcmptkpe2en0y5t75x2lrwu6yt5ljjkufhqtn8ty5sk93psa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBd0diTGlFVkFGS1hBRzlN
            VVNxN3F2a3JKZzB4am5QZkx4TXBoSUZrc0RVClkydXQ4U3JqVnJhTU1IcDBERFcv
            WWl3bzk4NXd2OGw3S3lWRkZOaXR1MjAKLS0tIGNVdmM1czR4OGE3ZkhWbmN4ZkpG
            dTZnRDNOa0RkT01oRWphTDdZQy9VdUUKhM8cm6UnvrZdVa/rIBbm1hUVKXH3nC4l
            n02fvut54sFeU4C546tlDzHkOX5jy0J+aCyIUiYHjn1lE9OVYmHVVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-02T05:57:54Z"
    mac: ENC[AES256_GCM,data:zkS1De22Z58BgD2ZdtCR951pFcKhQuNV79pqRgXR63gM/DgxYubL6VEN4sGhi6hwilzcEjyPVADwszqz8yHMuQczsIBdtTzhMVypWXtnlZC4ivwaWmg3H4rOgmjtbrsfUfbBny83gDjk2VASooCX60p0sMi73qqyr8JmGEY0R4o=,iv:Py2a2fUnwrEBUYH01yN9xLvswbxznqy6g169rpkmlfI=,tag:EcikqvBayLKLGhiVVir/Og==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
