kind: Secret
ansible_user: ENC[AES256_GCM,data:QIE=,iv:LiQDlnakmg44so/TSwlZK52nfB5NK/qBBgOiK35UWYc=,tag:sbQi4x0iwPo1ItXleK/jVg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:xeMTHPRdBQ==,iv:viHtDGKi/qO1I6Wd/KjpFuJ6JUL56Zi/f9EjMa2ePGU=,tag:LxWBaO8P215RDfDy5W0F3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lhe4v2xrzmjcmptkpe2en0y5t75x2lrwu6yt5ljjkufhqtn8ty5sk93psa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOHRXeTdzZmlxTlRla3BZ
            Qy9sNlpnang2VkNDY2FqWVFDd3M1b3I2SEVnCkx0c1JlSnJnSnlOd1VOUlY4R1Bi
            S01RMnNRcmF5akU4bHV5U0VEdysvYU0KLS0tIHg1ZVpPYXNoUkZVVWN0cHNTSlpo
            QkcwZDBLTTF2Qm9VNjVacTJCNy9PMTQKqgGC+WqWdnOFt2lF/gS5RNv57O2dogsN
            sUUkUPKzBoGqsqHNMThrAN67JL7xfK0vqPuMfxNsa69k6FPdnbhQ4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-02T05:57:54Z"
    mac: ENC[AES256_GCM,data:Z7NtqZWRYdK0wXqeQBunOzHyC0fzGEXhLejXEhx08vw6/n1RawSmWnOf+br6tm6sxTprBJkDQ2ArEAtSyZ8ingCUapXegMwNcP0sIvE/kvv4JJ02g4e7ofuR1+1t+9NiyQM0x57a6gI1Josey9hVs4c6A/E6wnI9TjIcvilz7VQ=,iv:zKyC48pKbJT8fBx1hAwSkmQLqDnipGW2oRj77RKsvCc=,tag:3m/1Ub0UCV7XLN35wcbQEw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
