kind: Secret
ansible_user: ENC[AES256_GCM,data:vCkebY5+3Q==,iv:OAQjzVWPJEH5Tlq1QTEpBF+Vk1Q1HLFH5SQo0Ru6V3s=,tag:EdI0LyKnO4dOkuu4TJJBHQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:VqAYZjSGhw==,iv:RgsFCgVZgWrcsY0NAazYn1HbbjsT0n6ASWsLm+MolZs=,tag:9RXAanEBEbIV83WQXZi1fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lhe4v2xrzmjcmptkpe2en0y5t75x2lrwu6yt5ljjkufhqtn8ty5sk93psa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWGNKZW9oamNxbzhtV3pL
            N0tlNmFPSlhjbjFicWJhdDE5N2lKRC9IQmxVCnlqb1I2ZG9vajdvV3RrSzM1QjZZ
            cExFNWRmTUF6WFhuL0QrQjd2WnlHR2cKLS0tIFFWaVVyYnkrK0VmQmJ6YW9QQzBu
            VE9CUHBJRm9tTGI4TW5uakVBK0tsYXMKw+jD6dKQLjsnLd7/NeYHRtM+I1pIyi2Y
            6BgcLOaK0qrR3g/TTZHZxsd/cqF61MpprqE7grzH/EwXJD757R688w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-01T10:01:28Z"
    mac: ENC[AES256_GCM,data:GDYAZf3l+wb8vpG/w2kCkP0vRoiQPZN+UBnVAM4EOum5QPQXy+gUebMI0gcit7KaI/R4SyxWr+KQjG7HGSrrzcYVAm0uZpGRrDNrszPbvskQqG6PZ1YZD8oAE4t3TV7r/5Nmqg4b0oij1O6ht3QBwtkiEJNFVal7ZLtmeMNePhw=,iv:uedbF4G3ghG1WAZSG0veiprnXfuyGJvYbXvQLryaaVM=,tag:L5nERc28lkFT+oqBO7Q5/g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
