kind: Secret
ansible_user: ENC[AES256_GCM,data:qVXvRICutA==,iv:sV41h0g4aOvyJUtJnGG6FmrsUe8RRtGkXyNlN927jFQ=,tag:A+VhBnhlxh7I00N+/9AJlQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ywFZc/qy/g==,iv:edRRFCSnAxK8oz9+CWO3zmbuJRUESZf70ggMgOSVVXs=,tag:p2yyeXX+QvSSmfSYYE+CEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lhe4v2xrzmjcmptkpe2en0y5t75x2lrwu6yt5ljjkufhqtn8ty5sk93psa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSlU3N3hXaFpRRWJOZHFz
            M0NSZEh3VFR1MU16WGQzTmJzN3lRcGxrdEZBCmQwd3ZSSmhmUFMxOTFGY2hrZzgz
            UldSNVZVYUJpM3pxbDdKTDJqRzEraTQKLS0tIHJCMkFHa3A0RjNIREtzU2p5MWpr
            RytSNmlGMFlhNmdNeVk2cVNkcENaeVkKdoijwrFwtF697xY5j/8dD9WaEbek2uaP
            P6ZX0Fmwi6+WXaey6muPf5CtNB9M+lOvHoeh1YWjT3kVf73NfTeiQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-01T10:01:28Z"
    mac: ENC[AES256_GCM,data:GKZyBAzY+2hsVDbo7PTtocF0frck/2mUcwxQWkHBMrNr8iDPsQg59twjmbq+VhcCBmJFue9tbRKvfo+hQFoPLXc/uPgvyWdqMsZT1oRkJJCD568JJQVVIQFMvTi3OYciqqePE19hmVIKXluVRNYzQhlg2xQySRk4JqE/0ghRnj8=,iv:riMDQx31resgEz0aqRtAdiyRemaikaqyzuMyRa/kKKU=,tag:t8jcwcZapzLlYnhDtwhExQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
