kind: Secret
ansible_user: ENC[AES256_GCM,data:U7siwivWDA==,iv:+7ZGuzU3ZQZtKh+Cnx5onbaImC11BroKw7mHBZhwqGs=,tag:/QRkARSxercJbQfUHv17wg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:C/o2OTv7CQ==,iv:hTLoz4IgIL1B5qGYstHNW4tX5/qLlLfyUpANiyukwgs=,tag:rZai5WCojRv4kfXmvNdAFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lhe4v2xrzmjcmptkpe2en0y5t75x2lrwu6yt5ljjkufhqtn8ty5sk93psa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM0ZtaFkxZ3Q4OS9aSWl3
            WkR1dzFDMHdYZkcvaHpRUldRWDNQd2hXRkNVCmhNdWRxcytjT1lKVnFwVXhhUVlp
            M3ZsYkZrcUhLNHF4bWpRaXY1Y3pIeUEKLS0tIHdsYXVCaFR5Y2F3NzlzTzg4U0ov
            VUlxYmx5MWdMamNRTDRxZzBLRTBIV0UKYEn2R90T92KXtsJaoi627UEknIL52vN5
            FsAb2PDGkqhtelkToE5yNgcW1nhXuj0aOurO4bQ+MH3LOdU70I9Dkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-01T23:42:34Z"
    mac: ENC[AES256_GCM,data:C0jbJlNWcZ9XiVVpwia9aVKfdGxOkE6crVGrRnO3USLfXEP5EYbqEFLKq42+KOtfnG4C6SHOdXjno6dnQvcL3ay5ORw3jWhiRIMbn3qLq9HbUQtInYRkKgMsDf4ROTzF2qhFWyf44GtzdM3oiFWc+8GTVxSpneXQLO0dn06R8ZM=,iv:tz5dESaNQAsUvmBGg9E+RkGbDg1og/x3Uc1wcJY0LnY=,tag:07iJOq+1wgvx1x5h8sa6zQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
