# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:dteJKoxyAEynf5wcboepC9W0ts1EsnB/wQOEwEe8wK98eOLodQ==,iv:f8EAPqyc6ayuSKUFeHs2wf17gnK0nWZWuhwPlmKTkFE=,tag:+3XIJ/EmAjRCRGjJBFag2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lhe4v2xrzmjcmptkpe2en0y5t75x2lrwu6yt5ljjkufhqtn8ty5sk93psa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOFNjTS9CWlhCSjBnQUt3
            eVBCS2RPMTd3cDlCeTVKdjg0cjhpNmp4aXo4Cm5XQ09DY2grR3NuRHNwUFpQL3Ji
            TUhNZG8vQXJkVTZ4bjdvSHN6ZWxxRVUKLS0tIHVqS1M2TDBpQ3NrWUc4aCtYR0cr
            Sm5TcDlZbk1SblprYVpyLzJ5cVhWMHcKOw0koUwtReOlgkDDjPCKx7I920bodMVv
            nhFLMiet7t4DMhudJwI2X6XbSbaFAwrRiE2SLNG0J3Qy6vplaqxjBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-01T23:42:34Z"
    mac: ENC[AES256_GCM,data:qMlWXlcU+4OnjvoK+NP5qFtcSDeNnoel8DbXj8yETnaABXiYGFR5z95MXw+xZApm1zSUgb/tiiIZPB1voq/+Frfn421eNmjJz4XuTqzAvl30mBOTa6xLNW7JAgcPEZH67edg297lPsAnu7ahsFeJaJFUKPsEVGw3oadt4Jc1Lek=,iv:juT/TyHn34hZFq7PQaHZSKb0F293Ctf7zX0PEXhuvmg=,tag:JZFaJ6qFzZbgqF3lCTlQYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
